# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e98101a775f00b22a87946b8633db35cdf67926167737427caac1981d13b70e1b10a39efede0ea1105516ccbf224f57d77ced7fc99b28edef3c64c1c969bef1

test:
  secret_key_base: 37e7ff2233220f508bf151eec3c645dd3d0e7bcc4c5bb427f73fba54548a387c2d3bf89ceaba95a0fbe92813d46fa958e680d49dac663249c8ddf55b0c9f236c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
